# GoReleaser configuration for synq-monitors CLI
# https://goreleaser.com/

# Build configuration
builds:
  - id: synq-monitors
    binary: synq-monitors
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# Archive configuration
archives:
  - id: default
    name_template: "synq-monitors_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - examples/*.yaml
      - sample_config.yaml

# Checksums
checksum:
  name_template: 'checksums.txt'

# Snapshots
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Release configuration
release:
  github:
    owner: getsynq
    name: synq-monitors
  draft: false
  prerelease: auto
  mode: replace
  name_template: "synq-monitors {{ .Tag }}"
  header: |
    ## What's Changed
    
    Full Changelog: https://github.com/getsynq/synq-monitors/compare/{{ .PreviousTag }}...{{ .Tag }}
  footer: |
    ## Installation
    
    ### macOS
    ```bash
    # Intel
    curl -L https://github.com/getsynq/synq-monitors/releases/download/{{ .Tag }}/synq-monitors_{{ .Version }}_darwin_amd64.tar.gz | tar -xz
    sudo mv synq-monitors /usr/local/bin/
    
    # Apple Silicon
    curl -L https://github.com/getsynq/synq-monitors/releases/download/{{ .Tag }}/synq-monitors_{{ .Version }}_darwin_arm64.tar.gz | tar -xz
    sudo mv synq-monitors /usr/local/bin/
    ```
    
    ### Linux
    ```bash
    # AMD64
    curl -L https://github.com/getsynq/synq-monitors/releases/download/{{ .Tag }}/synq-monitors_{{ .Version }}_linux_amd64.tar.gz | tar -xz
    sudo mv synq-monitors /usr/local/bin/
    
    # ARM64
    curl -L https://github.com/getsynq/synq-monitors/releases/download/{{ .Tag }}/synq-monitors_{{ .Version }}_linux_arm64.tar.gz | tar -xz
    sudo mv synq-monitors /usr/local/bin/
    ```
    
    ### Windows
    Download the appropriate zip file and extract `synq-monitors.exe` to your PATH.

# Homebrew formula (optional - uncomment if you want to publish to Homebrew)
# brew:
#   github:
#     owner: getsynq
#     name: homebrew-tap
#   folder: Formula
#   description: "Deploy custom monitors from YAML configuration"
#   homepage: "https://github.com/getsynq/synq-monitors"
#   license: "MIT"
#   skip_upload: false
#   test:
#     commands:
#       - system "#{bin}/synq-monitors --help"
