defaults:
  severity: WARNING

monitors:
  - id: volume
    name: "Zdenko test config mgmt renamed"
    type: volume
    time_partitioning: "scheduled_at"
    monitored_id: ch-prod::anomalies::corrections_v2

  - id: volume_by_workspace
    name: "Zdenko test config mgmt by workspace renamed"
    type: volume
    time_partitioning: "scheduled_at"
    segmentation: "workspace"
    monitored_ids:
      - ch-prod::anomalies::corrections_v2

  - id: custom_numeric_active_users
    type: custom_numeric
    metric_aggregation: "COUNT(DISTINCT status)"
    time_partitioning: "order_date"
    monitored_ids:
      - bq-synq-dwh::test::orders
    mode:
      fixed_thresholds:
        min: 100
        max: 10000
    schedule:
      hourly: 15
